<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "heiner"
 *
 * Auto generated by Extension Builder 2021-06-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'personenundfirmen',
    'description' => 'Extension mit CRUD-Funktion für Personen und Firmeneinträge',
    'category' => 'plugin',
    'author' => 'Heiner Giehl',
    'author_email' => 'heiner.giehl@tu-dortmund.de',
    'state' => 'alpha',
    'uploadfolder' => '',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
